version: "3"
services:
  proxy:
    image: jwilder/nginx-proxy
    container_name: opa-nginx-proxy
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    ports:
      - "80:80"

  user:
    build: ./user
    image: opa/user
    container_name: opa-user
    depends_on:
      - db
      - proxy
      - share
    links:
      - db
    environment:
      VIRTUAL_HOST: opa-user.local

  auth:
    build: ./auth
    image: opa/auth
    container_name: opa-auth
    depends_on:
      - db
      - proxy
      - share 
    ports: 
      - 3001:3001
    links:
      - db
    environment:
      VIRTUAL_HOST: opa-auth.local

  share:
    build: ./share
    image: opa/share
    
  db: 
    image: rethinkdb:latest
    container_name: opa-db
    ports: 
      - "28015:28015"
      - "29015:29015"
      - "8080:8080"
    volumes:
      - ./backup:/backup:rw
      
